config/routes.rb
Rails.application.routes.draw do


  # get 'tasks/index'

  # get 'tasks/show'

  # get 'tasks/new'

  # get 'tasks/create'

  # get 'tasks/edit'

  # get 'tasks/update'

  # get 'tasks/destroy'

get '/tasks', to: 'tasks#index'
post '/tasks', to: 'tasks#create'
get '/tasks/new', to: 'tasks#new'
get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
get '/tasks/:id', to: 'tasks#show', as: 'task'
patch '/tasks/:id', to: 'tasks#update'
delete '/tasks/:id', to: 'tasks#destroy'

# resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @task = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end


  def destroy
     @task = Task.find(params[:id])
     @task.destroy
      redirect_to tasks_path


  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>

  <%= f.label :details, "Enter details of this task" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>


<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>



<%= @task=Task.new %>

<%= form_for(@task) do |f| %>
  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>

  <%= f.label :details, "Enter details of this task" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
<% @task.each do |task| %>
  <li><%= link_to task.title, task_path(task) %></li>
  <li><%= task.details %></li>
<%= link_to("Delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" } ) %></p>
  <% end %>
</ul>

<ul>
  <li><%= link_to "new", tasks_new_path %></li>
</ul>

app/views/tasks/new.html.erb
<h1>Add task</h1>

<%= @task=Task.new %>
<%= form_for(@task) do |f| %>
  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>

  <%= f.label :details, "Enter details of this task" %>
  <%= f.text_field :details %>
  <%= f.submit %>





<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<li><%= link_to "edit", edit_task_path(@task) %></li>
<li><%= link_to "delete", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %></li>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>


  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>

  <%= f.label :details, "Enter details of this task" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p>Find me in app/views/tasks/update.html.erb</p>